name: build-latex
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-full imagemagick python3
          version: 1.1
          execute_install_scripts: true
      - name: Run script
        run: |
          sh ./run.sh
      - name: Publish results to 'export' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: export
